### ISSUE TITLE
Hide fab while scrolling and set an icon to fab

### ISSUE THREAD

**Issue by FirstSafetyFirst** [FirstSafetyFirst/FirstSafetyFirst#11]
![device-2017-10-15-112115](https://user-images.githubusercontent.com/32449431/31582229-7d798624-b19b-11e7-91a2-2e3695191b85.png)

**Comment by zeerorg** [comment]
@vikasmahato  close this issue ??

**Comment by vikasmahato** [comment]
not yet...it has not been merged yet

**Comment by zeerorg** [comment]
Okay !!
