### ISSUE TITLE
Multiple image select in post Image

### ISSUE THREAD

**Issue by zeerorg** [FirstSafetyFirst/FirstSafetyFirst#15]
Display notification while posting image

**Comment by zeerorg** [comment]
I will work on creating a sperate module for image selection task.

**Comment by FirstSafetyFirst** [comment]
@zeerorg  On submitting with Multiple images close new post activity and create  a toast saying that The post will be updated soon . Check notif bar for progress and create a progress bar in nofication panel which displays the progress of post upload with an option to retry just like it is in facebook

**Comment by zeerorg** [comment]
I think some modifications are also left like downscaling images.
So I have to do:
1. Create notification for progress upload
2. Show toast for image upload
3. Downscaling images.
4. Creating thumbnails (discussion on this point)

**Comment by FirstSafetyFirst** [comment]
Good work!!
